"""init

Revision ID: 0ee9097c93e0
Revises: 
Create Date: 2026-06-04 22:38:37.479658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee9097c93e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('payment_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('routing_key', sa.String(length=128), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_event_created_at'), 'payment_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_event_event_type'), 'payment_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_event_payment_id'), 'payment_event', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_event_published'), 'payment_event', ['published'], unique=False)
    op.create_index(op.f('ix_payment_event_retry_count'), 'payment_event', ['retry_count'], unique=False)
    op.create_index(op.f('ix_payment_event_routing_key'), 'payment_event', ['routing_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_event_routing_key'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_retry_count'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_published'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_payment_id'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_event_type'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_created_at'), table_name='payment_event')
    op.drop_table('payment_event')
    op.drop_table('idempotency_key')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
